### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by greysoftcrazy** [kettle11/koi#3] opened 2023-03-12 04:10 UTC
./run.sh hello
error: failed to load manifest for workspace member `/home/greysoft/temp/koi/crates/kreflect`

Caused by:
  failed to read `/home/greysoft/temp/koi/crates/kreflect/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
cp: не удалось выполнить stat для 'target/wasm32-unknown-unknown/release/examples/hello.wasm': Нет такого файла или каталога
cp: невозможно создать обычный файл 'web_build/kwasm.js': Нет такого файла или каталога
Path [/home/greysoft/temp/koi/web_build] does not exist!

**Comment by kettle11** [comment] 2023-03-12 04:25
I suspect the issue is that kreflect's `Cargo.toml` file was lowercased as `cargo.toml` for some reason, which is non-standard. 

I've pushed a fix: https://github.com/kettle11/koi/commit/e9281e8219fa553b9d88c11b6505e7e5cf27c781

Let me know if this works!

**Comment by greysoftcrazy** [comment] 2023-03-12 04:31
Ok, the simplest mistake, I didn’t notice it myself, I thought that everything was complicated

**Closed** 2023-03-12 04:31 UTC

**Comment by kettle11** [comment] 2023-03-12 04:34
Thanks for reporting! I would have never noticed otherwise because I'm using a case-insensitive operating system.
